// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muadbgzciuwujheataxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11YWRiZ3pjaXV3dWpoZWF0YXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzEwNjYsImV4cCI6MjA1ODc0NzA2Nn0.enbkvfJ2bAJrKxt4MbZusGdtT2kOTWD3WDKWkYBI7bA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);